### ISSUE TITLE
Error in new mainSpotifyEPD.py

### ISSUE THREAD

**Issue by DerFredx** [alexthescott/ePaper-Spotify-Clock#11]
Hey,

after updating the mainSpotifyEPD.py to your newest released version, I doesn't run.
That's the error message:

root@raspberrypi:~# bash launch_epaper.sh
  File "mainSpotifyEPD.py", line 316
    URL_UNITS = "&units=metric" if metric_units else url_units = "&units=imperial"
               ^
SyntaxError: can't assign to conditional expression

**Comment by alexthescott** [comment]
Just pushed another update fixing that conditional statement!

**Comment by DerFredx** [comment]
Now it works fine, thank you very much.

Best wishes,

Fred

alexthescott <notifications@github.com> schrieb am Di., 27. Okt. 2020,
18:13:
