### ISSUE TITLE
"New bug caught 'main'"

### ISSUE THREAD

**Issue by jpgamboa** [alexthescott/ePaper-Spotify-Clock#15]
Trying to run this directly from python and get the following, but I'm unable to diagnose its origin: 

```
python3 mainSpotifyEPD.py

2:40am

new bug caught

'main'

Retrying main_loop() in 20 seconds...
```

The ePaper doesn't render during this time and the bugs.txt file only has one line: 'main'

What's the origin of this?

Thanks!

**Comment by jpgamboa** [comment]
Based on the code, the only time 'main' appears is in the OpenWeather API. Going to play around to see if I missed something in my config.

**Comment by jpgamboa** [comment]
Looks like the OpenWeatherMap API didn't like that I left the OW_OTHER_CITY field empty. Putting in the same city in the field fixed it.

**Comment by alexthescott** [comment]
Hey John! Glad you squashed this issue. Let me know if there's any changes I could make to make the debugging process easier. I put a boolean flag towards the top of the file called hide_other_weather, and the request to grab OW_OTHER_CITY shouldn't execute if hide_other_weather is true. That's the hope anyway.

- Alex
