### ISSUE TITLE
IndentationError: unexpected unindent - localJsonIO.py

### ISSUE THREAD

**Issue by DerFredx** [alexthescott/ePaper-Spotify-Clock#9]
Hey,

you get an error by executing the new localJsonIO.py.
It says:

root@raspberrypi://root# bash launch_epaper.sh
Traceback (most recent call last):
  File "mainSpotifyEPD.py", line 38, in <module>
    import localJsonIO as contextIO
  File "/home/pi/ePaper-Spotify-Clock-master/ePaper-Spotify-Clock-master/localJsonIO.py", line 35
    context_data = {}
    ^
IndentationError: unexpected unindent

**Comment by alexthescott** [comment]
Great catch! Looks like my try block was missing a catch block. localJsonIO.py now has a catch block on line 36, squashing the IndentationError
